# Generated by Django 2.0.5 on 2019-02-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCamera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 't_camera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TPictureCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm.TCamera')),
            ],
            options={
                'db_table': 't_picture_camera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TPictureUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 't_picture_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUidPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orm.TPictureCamera')),
            ],
            options={
                'db_table': 't_uid_picture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_uid', models.CharField(max_length=128)),
                ('account', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 't_uid_user',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='tuiduser',
            unique_together={('face_uid', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='tuidpicture',
            unique_together={('uid', 'picture')},
        ),
    ]
