# Generated by Django 2.0.5 on 2018-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpicturecamera',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tpictureuser',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='account',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tuidpicture',
            unique_together={('uid', 'picture')},
        ),
        migrations.AlterUniqueTogether(
            name='tuiduser',
            unique_together={('face_uid', 'user')},
        ),
    ]
