# Generated by Django 2.0.5 on 2019-02-22 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpictureuser',
            name='size',
            field=models.FloatField(blank=True, null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='tpictureuser',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
    ]
