# Generated by Django 2.0.5 on 2018-09-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180801_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='tuser',
            name='phone_number',
            field=models.CharField(blank=True, default=123, max_length=128),
            preserve_default=False,
        ),
    ]
