# Generated by Django 2.0.5 on 2018-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_tuser_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='time',
            field=models.TimeField(),
        ),
    ]
