# Generated by Django 2.0.5 on 2018-06-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20180610_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
