# Generated by Django 2.0.5 on 2018-07-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_auto_20180610_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='biography',
        ),
    ]
