# Generated by Django 2.0.5 on 2018-07-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_remove_tuser_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpicturecamera',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tpictureuser',
            options={'managed': True},
        ),
    ]
